# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arrive_form.ui'
#
# Created: Tue Jul 12 02:35:29 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(620, 561)
        Dialog.setMinimumSize(QtCore.QSize(0, 42))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/arrive")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.fotoBox = QtGui.QGroupBox(Dialog)
        self.fotoBox.setGeometry(QtCore.QRect(15, 92, 604, 411))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fotoBox.sizePolicy().hasHeightForWidth())
        self.fotoBox.setSizePolicy(sizePolicy)
        self.fotoBox.setMinimumSize(QtCore.QSize(400, 400))
        self.fotoBox.setObjectName(_fromUtf8("fotoBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.fotoBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 581, 381))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.fotoLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.fotoLayout.setMargin(0)
        self.fotoLayout.setObjectName(_fromUtf8("fotoLayout"))
        self.fotoButtonBox = QtGui.QGroupBox(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fotoButtonBox.sizePolicy().hasHeightForWidth())
        self.fotoButtonBox.setSizePolicy(sizePolicy)
        self.fotoButtonBox.setMinimumSize(QtCore.QSize(102, 70))
        self.fotoButtonBox.setStyleSheet(_fromUtf8("#fotoButtonBox {border: none;}"))
        self.fotoButtonBox.setTitle(_fromUtf8(""))
        self.fotoButtonBox.setObjectName(_fromUtf8("fotoButtonBox"))
        self.makeFoto = QtGui.QPushButton(self.fotoButtonBox)
        self.makeFoto.setGeometry(QtCore.QRect(5, 5, 90, 26))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeFoto.sizePolicy().hasHeightForWidth())
        self.makeFoto.setSizePolicy(sizePolicy)
        self.makeFoto.setMinimumSize(QtCore.QSize(90, 26))
        self.makeFoto.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/webcam")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.makeFoto.setIcon(icon1)
        self.makeFoto.setObjectName(_fromUtf8("makeFoto"))
        self.openFoto = QtGui.QPushButton(self.fotoButtonBox)
        self.openFoto.setGeometry(QtCore.QRect(5, 35, 90, 26))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFoto.sizePolicy().hasHeightForWidth())
        self.openFoto.setSizePolicy(sizePolicy)
        self.openFoto.setMinimumSize(QtCore.QSize(90, 26))
        self.openFoto.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open_image")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFoto.setIcon(icon2)
        self.openFoto.setObjectName(_fromUtf8("openFoto"))
        self.fotoLayout.addWidget(self.fotoButtonBox)
        self.fotoArea = QtGui.QGraphicsView(self.horizontalLayoutWidget)
        self.fotoArea.setObjectName(_fromUtf8("fotoArea"))
        self.fotoLayout.addWidget(self.fotoArea)
        self.fieldsBox = QtGui.QGroupBox(Dialog)
        self.fieldsBox.setGeometry(QtCore.QRect(16, 1, 601, 90))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldsBox.sizePolicy().hasHeightForWidth())
        self.fieldsBox.setSizePolicy(sizePolicy)
        self.fieldsBox.setMinimumSize(QtCore.QSize(601, 90))
        self.fieldsBox.setTitle(_fromUtf8(""))
        self.fieldsBox.setObjectName(_fromUtf8("fieldsBox"))
        self.is_cure = QtGui.QCheckBox(self.fieldsBox)
        self.is_cure.setGeometry(QtCore.QRect(480, 22, 80, 17))
        self.is_cure.setObjectName(_fromUtf8("is_cure"))
        self.send_address_id = QtGui.QComboBox(self.fieldsBox)
        self.send_address_id.setGeometry(QtCore.QRect(280, 50, 171, 22))
        self.send_address_id.setObjectName(_fromUtf8("send_address_id"))
        self.arrive_date = QtGui.QDateEdit(self.fieldsBox)
        self.arrive_date.setGeometry(QtCore.QRect(57, 20, 110, 22))
        self.arrive_date.setCalendarPopup(True)
        self.arrive_date.setObjectName(_fromUtf8("arrive_date"))
        self.label_3 = QtGui.QLabel(self.fieldsBox)
        self.label_3.setGeometry(QtCore.QRect(20, 53, 31, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.leave_cause_id = QtGui.QComboBox(self.fieldsBox)
        self.leave_cause_id.setGeometry(QtCore.QRect(280, 20, 170, 22))
        self.leave_cause_id.setObjectName(_fromUtf8("leave_cause_id"))
        self.label_2 = QtGui.QLabel(self.fieldsBox)
        self.label_2.setGeometry(QtCore.QRect(10, 22, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.fieldsBox)
        self.label_4.setGeometry(QtCore.QRect(228, 22, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.leave_date = QtGui.QDateEdit(self.fieldsBox)
        self.leave_date.setGeometry(QtCore.QRect(57, 50, 110, 22))
        self.leave_date.setCalendarPopup(True)
        self.leave_date.setObjectName(_fromUtf8("leave_date"))
        self.send_address_id_label = QtGui.QLabel(self.fieldsBox)
        self.send_address_id_label.setGeometry(QtCore.QRect(190, 53, 90, 13))
        self.send_address_id_label.setObjectName(_fromUtf8("send_address_id_label"))
        self.buttonBox = QtGui.QGroupBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(13, 510, 340, 42))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(340, 42))
        self.buttonBox.setStyleSheet(_fromUtf8("#buttonBox {border: none;}"))
        self.buttonBox.setTitle(_fromUtf8(""))
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.closeButton = QtGui.QPushButton(self.buttonBox)
        self.closeButton.setGeometry(QtCore.QRect(230, 6, 100, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMinimumSize(QtCore.QSize(100, 30))
        self.closeButton.setMaximumSize(QtCore.QSize(100, 30))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.deleteButton = QtGui.QPushButton(self.buttonBox)
        self.deleteButton.setGeometry(QtCore.QRect(120, 6, 100, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setMinimumSize(QtCore.QSize(100, 30))
        self.deleteButton.setMaximumSize(QtCore.QSize(100, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/delete_arrive")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon3)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.saveButton = QtGui.QPushButton(self.buttonBox)
        self.saveButton.setGeometry(QtCore.QRect(7, 6, 100, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(100, 30))
        self.saveButton.setMaximumSize(QtCore.QSize(100, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/add_arrive")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon4)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Прибытие/убытие", None, QtGui.QApplication.UnicodeUTF8))
        self.fotoBox.setTitle(QtGui.QApplication.translate("Dialog", "Фото прибытия", None, QtGui.QApplication.UnicodeUTF8))
        self.makeFoto.setText(QtGui.QApplication.translate("Dialog", "Снять", None, QtGui.QApplication.UnicodeUTF8))
        self.openFoto.setText(QtGui.QApplication.translate("Dialog", "Открыть", None, QtGui.QApplication.UnicodeUTF8))
        self.is_cure.setText(QtGui.QApplication.translate("Dialog", "Долечился", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Убыл", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Прибыл", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Причина", None, QtGui.QApplication.UnicodeUTF8))
        self.send_address_id_label.setText(QtGui.QApplication.translate("Dialog", "Адрес отправки", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("Dialog", "Закрыть", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("Dialog", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("Dialog", "Сохранить", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
