# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catalogs_form.ui'
#
# Created: Tue Jul 12 02:28:45 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(362, 300)
        Dialog.setMinimumSize(QtCore.QSize(335, 300))
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.tabs = QtGui.QTabWidget(Dialog)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 351, 281))
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.addictionTab = QtGui.QWidget()
        self.addictionTab.setObjectName(_fromUtf8("addictionTab"))
        self.verticalLayoutWidget = QtGui.QWidget(self.addictionTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 251))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.addictionLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.addictionLayout.setMargin(0)
        self.addictionLayout.setObjectName(_fromUtf8("addictionLayout"))
        self.addictionTable = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.addictionTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.addictionTable.setObjectName(_fromUtf8("addictionTable"))
        self.addictionTable.setColumnCount(1)
        self.addictionTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.addictionTable.setHorizontalHeaderItem(0, item)
        self.addictionTable.horizontalHeader().setVisible(False)
        self.addictionTable.horizontalHeader().setStretchLastSection(True)
        self.addictionTable.verticalHeader().setVisible(True)
        self.addictionLayout.addWidget(self.addictionTable)
        self.addictionButtonsLayout = QtGui.QHBoxLayout()
        self.addictionButtonsLayout.setObjectName(_fromUtf8("addictionButtonsLayout"))
        self.addAddiction = QtGui.QPushButton(self.verticalLayoutWidget)
        self.addAddiction.setMinimumSize(QtCore.QSize(100, 30))
        self.addAddiction.setMaximumSize(QtCore.QSize(100, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/add_line")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addAddiction.setIcon(icon)
        self.addAddiction.setObjectName(_fromUtf8("addAddiction"))
        self.addictionButtonsLayout.addWidget(self.addAddiction)
        self.editAddiction = QtGui.QPushButton(self.verticalLayoutWidget)
        self.editAddiction.setMinimumSize(QtCore.QSize(100, 30))
        self.editAddiction.setMaximumSize(QtCore.QSize(100, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/edit_line")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editAddiction.setIcon(icon1)
        self.editAddiction.setObjectName(_fromUtf8("editAddiction"))
        self.addictionButtonsLayout.addWidget(self.editAddiction)
        self.deleteAddiction = QtGui.QPushButton(self.verticalLayoutWidget)
        self.deleteAddiction.setMinimumSize(QtCore.QSize(100, 30))
        self.deleteAddiction.setMaximumSize(QtCore.QSize(100, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/delete_line")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteAddiction.setIcon(icon2)
        self.deleteAddiction.setObjectName(_fromUtf8("deleteAddiction"))
        self.addictionButtonsLayout.addWidget(self.deleteAddiction)
        self.addictionLayout.addLayout(self.addictionButtonsLayout)
        self.tabs.addTab(self.addictionTab, _fromUtf8(""))
        self.addressTab = QtGui.QWidget()
        self.addressTab.setObjectName(_fromUtf8("addressTab"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.addressTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 341, 251))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.addressLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.addressLayout.setMargin(0)
        self.addressLayout.setObjectName(_fromUtf8("addressLayout"))
        self.addressTable = QtGui.QTableWidget(self.verticalLayoutWidget_2)
        self.addressTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.addressTable.setObjectName(_fromUtf8("addressTable"))
        self.addressTable.setColumnCount(1)
        self.addressTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.addressTable.setHorizontalHeaderItem(0, item)
        self.addressTable.horizontalHeader().setVisible(False)
        self.addressTable.horizontalHeader().setStretchLastSection(True)
        self.addressLayout.addWidget(self.addressTable)
        self.addressButtonsLayout = QtGui.QHBoxLayout()
        self.addressButtonsLayout.setObjectName(_fromUtf8("addressButtonsLayout"))
        self.addAddress = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.addAddress.setMinimumSize(QtCore.QSize(100, 30))
        self.addAddress.setMaximumSize(QtCore.QSize(100, 30))
        self.addAddress.setObjectName(_fromUtf8("addAddress"))
        self.addressButtonsLayout.addWidget(self.addAddress)
        self.editAddress = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.editAddress.setMinimumSize(QtCore.QSize(100, 30))
        self.editAddress.setMaximumSize(QtCore.QSize(100, 30))
        self.editAddress.setObjectName(_fromUtf8("editAddress"))
        self.addressButtonsLayout.addWidget(self.editAddress)
        self.deleteAddress = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.deleteAddress.setMinimumSize(QtCore.QSize(100, 30))
        self.deleteAddress.setMaximumSize(QtCore.QSize(100, 30))
        self.deleteAddress.setObjectName(_fromUtf8("deleteAddress"))
        self.addressButtonsLayout.addWidget(self.deleteAddress)
        self.addressLayout.addLayout(self.addressButtonsLayout)
        self.tabs.addTab(self.addressTab, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Редактирование справочников", None, QtGui.QApplication.UnicodeUTF8))
        self.addictionTable.setSortingEnabled(True)
        self.addictionTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Зависимость", None, QtGui.QApplication.UnicodeUTF8))
        self.addAddiction.setText(QtGui.QApplication.translate("Dialog", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.editAddiction.setText(QtGui.QApplication.translate("Dialog", "Изменить", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteAddiction.setText(QtGui.QApplication.translate("Dialog", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.addictionTab), QtGui.QApplication.translate("Dialog", "Виды зависимости", None, QtGui.QApplication.UnicodeUTF8))
        self.addressTable.setSortingEnabled(True)
        self.addressTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Адрес", None, QtGui.QApplication.UnicodeUTF8))
        self.addAddress.setText(QtGui.QApplication.translate("Dialog", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.editAddress.setText(QtGui.QApplication.translate("Dialog", "Изменить", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteAddress.setText(QtGui.QApplication.translate("Dialog", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.addressTab), QtGui.QApplication.translate("Dialog", "Адреса отправки в адаптацию", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
