# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter_form.ui'
#
# Created: Tue Jul 12 01:22:33 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(464, 407)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/filter_big")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.born_date_from = QtGui.QDateEdit(Dialog)
        self.born_date_from.setEnabled(False)
        self.born_date_from.setGeometry(QtCore.QRect(180, 150, 110, 22))
        self.born_date_from.setCalendarPopup(True)
        self.born_date_from.setObjectName(_fromUtf8("born_date_from"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 5, 20, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(12, 5, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(311, 5, 51, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.born_date_label = QtGui.QLabel(Dialog)
        self.born_date_label.setEnabled(False)
        self.born_date_label.setGeometry(QtCore.QRect(180, 130, 84, 16))
        self.born_date_label.setObjectName(_fromUtf8("born_date_label"))
        self.gender = QtGui.QGroupBox(Dialog)
        self.gender.setGeometry(QtCore.QRect(10, 70, 112, 47))
        self.gender.setFlat(False)
        self.gender.setCheckable(False)
        self.gender.setObjectName(_fromUtf8("gender"))
        self.male = QtGui.QCheckBox(self.gender)
        self.male.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.male.setChecked(True)
        self.male.setObjectName(_fromUtf8("male"))
        self.female = QtGui.QCheckBox(self.gender)
        self.female.setGeometry(QtCore.QRect(59, 20, 47, 17))
        self.female.setChecked(True)
        self.female.setObjectName(_fromUtf8("female"))
        self.address_2 = QtGui.QLabel(Dialog)
        self.address_2.setGeometry(QtCore.QRect(170, 210, 86, 13))
        self.address_2.setObjectName(_fromUtf8("address_2"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(13, 130, 87, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.address = QtGui.QLineEdit(Dialog)
        self.address.setGeometry(QtCore.QRect(170, 230, 221, 20))
        self.address.setObjectName(_fromUtf8("address"))
        self.last_name = QtGui.QLineEdit(Dialog)
        self.last_name.setGeometry(QtCore.QRect(10, 20, 140, 20))
        self.last_name.setObjectName(_fromUtf8("last_name"))
        self.first_name = QtGui.QLineEdit(Dialog)
        self.first_name.setGeometry(QtCore.QRect(159, 20, 140, 20))
        self.first_name.setObjectName(_fromUtf8("first_name"))
        self.middle_name = QtGui.QLineEdit(Dialog)
        self.middle_name.setGeometry(QtCore.QRect(310, 20, 140, 20))
        self.middle_name.setObjectName(_fromUtf8("middle_name"))
        self.born_place = QtGui.QLineEdit(Dialog)
        self.born_place.setGeometry(QtCore.QRect(10, 150, 140, 20))
        self.born_place.setObjectName(_fromUtf8("born_place"))
        self.filterButton = QtGui.QPushButton(Dialog)
        self.filterButton.setGeometry(QtCore.QRect(10, 370, 90, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/filter")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filterButton.setIcon(icon1)
        self.filterButton.setObjectName(_fromUtf8("filterButton"))
        self.resetButton = QtGui.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(110, 370, 90, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/refresh")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetButton.setIcon(icon2)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.closeButton = QtGui.QPushButton(Dialog)
        self.closeButton.setGeometry(QtCore.QRect(210, 370, 90, 30))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 290, 91, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.born_date_label_from = QtGui.QLabel(Dialog)
        self.born_date_label_from.setEnabled(False)
        self.born_date_label_from.setGeometry(QtCore.QRect(168, 153, 12, 16))
        self.born_date_label_from.setObjectName(_fromUtf8("born_date_label_from"))
        self.born_date_label_to = QtGui.QLabel(Dialog)
        self.born_date_label_to.setEnabled(False)
        self.born_date_label_to.setGeometry(QtCore.QRect(301, 152, 17, 16))
        self.born_date_label_to.setObjectName(_fromUtf8("born_date_label_to"))
        self.born_date_to = QtGui.QDateEdit(Dialog)
        self.born_date_to.setEnabled(False)
        self.born_date_to.setGeometry(QtCore.QRect(320, 150, 110, 22))
        self.born_date_to.setCalendarPopup(True)
        self.born_date_to.setObjectName(_fromUtf8("born_date_to"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 210, 88, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.address_city = QtGui.QLineEdit(Dialog)
        self.address_city.setGeometry(QtCore.QRect(10, 230, 140, 20))
        self.address_city.setObjectName(_fromUtf8("address_city"))
        self.born_place_type = QtGui.QCheckBox(Dialog)
        self.born_place_type.setGeometry(QtCore.QRect(10, 170, 120, 17))
        self.born_place_type.setObjectName(_fromUtf8("born_place_type"))
        self.last_name_type = QtGui.QCheckBox(Dialog)
        self.last_name_type.setGeometry(QtCore.QRect(10, 40, 120, 17))
        self.last_name_type.setObjectName(_fromUtf8("last_name_type"))
        self.first_name_type = QtGui.QCheckBox(Dialog)
        self.first_name_type.setGeometry(QtCore.QRect(160, 40, 120, 17))
        self.first_name_type.setObjectName(_fromUtf8("first_name_type"))
        self.middle_name_type = QtGui.QCheckBox(Dialog)
        self.middle_name_type.setGeometry(QtCore.QRect(310, 40, 120, 17))
        self.middle_name_type.setObjectName(_fromUtf8("middle_name_type"))
        self.address_type = QtGui.QCheckBox(Dialog)
        self.address_type.setGeometry(QtCore.QRect(170, 250, 120, 17))
        self.address_type.setObjectName(_fromUtf8("address_type"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(190, 290, 136, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.addiction_type = QtGui.QComboBox(Dialog)
        self.addiction_type.setGeometry(QtCore.QRect(10, 310, 141, 22))
        self.addiction_type.setObjectName(_fromUtf8("addiction_type"))
        self.born_date_enabled = QtGui.QCheckBox(Dialog)
        self.born_date_enabled.setGeometry(QtCore.QRect(180, 172, 71, 17))
        self.born_date_enabled.setObjectName(_fromUtf8("born_date_enabled"))
        self.addiction_duration_from = QtGui.QLineEdit(Dialog)
        self.addiction_duration_from.setGeometry(QtCore.QRect(188, 310, 71, 20))
        self.addiction_duration_from.setText(_fromUtf8(""))
        self.addiction_duration_from.setObjectName(_fromUtf8("addiction_duration_from"))
        self.addiction_duration_to = QtGui.QLineEdit(Dialog)
        self.addiction_duration_to.setGeometry(QtCore.QRect(289, 310, 71, 20))
        self.addiction_duration_to.setText(_fromUtf8(""))
        self.addiction_duration_to.setObjectName(_fromUtf8("addiction_duration_to"))
        self.born_date_label_from_2 = QtGui.QLabel(Dialog)
        self.born_date_label_from_2.setEnabled(True)
        self.born_date_label_from_2.setGeometry(QtCore.QRect(170, 312, 15, 16))
        self.born_date_label_from_2.setObjectName(_fromUtf8("born_date_label_from_2"))
        self.born_date_label_from_3 = QtGui.QLabel(Dialog)
        self.born_date_label_from_3.setEnabled(True)
        self.born_date_label_from_3.setGeometry(QtCore.QRect(258, 313, 20, 16))
        self.born_date_label_from_3.setText(_fromUtf8(""))
        self.born_date_label_from_3.setObjectName(_fromUtf8("born_date_label_from_3"))
        self.born_date_label_from_4 = QtGui.QLabel(Dialog)
        self.born_date_label_from_4.setEnabled(True)
        self.born_date_label_from_4.setGeometry(QtCore.QRect(266, 311, 15, 16))
        self.born_date_label_from_4.setObjectName(_fromUtf8("born_date_label_from_4"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(161, 73, 105, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.passport = QtGui.QLineEdit(Dialog)
        self.passport.setGeometry(QtCore.QRect(160, 90, 160, 20))
        self.passport.setInputMask(_fromUtf8(""))
        self.passport.setText(_fromUtf8(""))
        self.passport.setObjectName(_fromUtf8("passport"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.last_name, self.last_name_type)
        Dialog.setTabOrder(self.last_name_type, self.first_name)
        Dialog.setTabOrder(self.first_name, self.first_name_type)
        Dialog.setTabOrder(self.first_name_type, self.middle_name)
        Dialog.setTabOrder(self.middle_name, self.middle_name_type)
        Dialog.setTabOrder(self.middle_name_type, self.male)
        Dialog.setTabOrder(self.male, self.female)
        Dialog.setTabOrder(self.female, self.born_place)
        Dialog.setTabOrder(self.born_place, self.born_place_type)
        Dialog.setTabOrder(self.born_place_type, self.born_date_from)
        Dialog.setTabOrder(self.born_date_from, self.born_date_to)
        Dialog.setTabOrder(self.born_date_to, self.address_city)
        Dialog.setTabOrder(self.address_city, self.address)
        Dialog.setTabOrder(self.address, self.address_type)
        Dialog.setTabOrder(self.address_type, self.filterButton)
        Dialog.setTabOrder(self.filterButton, self.resetButton)
        Dialog.setTabOrder(self.resetButton, self.closeButton)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Фильтр базы", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Имя", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Фамилия", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Отчество", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label.setText(QtGui.QApplication.translate("Dialog", "Дата рождения", None, QtGui.QApplication.UnicodeUTF8))
        self.gender.setTitle(QtGui.QApplication.translate("Dialog", "Пол", None, QtGui.QApplication.UnicodeUTF8))
        self.male.setText(QtGui.QApplication.translate("Dialog", "Муж.", None, QtGui.QApplication.UnicodeUTF8))
        self.female.setText(QtGui.QApplication.translate("Dialog", "Жен.", None, QtGui.QApplication.UnicodeUTF8))
        self.address_2.setText(QtGui.QApplication.translate("Dialog", "Адрес прописки", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Место рождения", None, QtGui.QApplication.UnicodeUTF8))
        self.filterButton.setText(QtGui.QApplication.translate("Dialog", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("Dialog", "Сбросить", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("Dialog", "Закрыть", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Тип зависимости", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_from.setText(QtGui.QApplication.translate("Dialog", "С", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_to.setText(QtGui.QApplication.translate("Dialog", "До", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Город прописки", None, QtGui.QApplication.UnicodeUTF8))
        self.born_place_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.last_name_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.first_name_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.middle_name_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.address_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Длительность (в годах)", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_enabled.setText(QtGui.QApplication.translate("Dialog", "включить", None, QtGui.QApplication.UnicodeUTF8))
        self.addiction_duration_from.setInputMask(QtGui.QApplication.translate("Dialog", "####; ", None, QtGui.QApplication.UnicodeUTF8))
        self.addiction_duration_to.setInputMask(QtGui.QApplication.translate("Dialog", "####; ", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_from_2.setText(QtGui.QApplication.translate("Dialog", "От", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_from_4.setText(QtGui.QApplication.translate("Dialog", "До", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Паспорт (Серия, №)", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
