# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter_form.ui'
#
# Created: Thu Jul 07 04:22:31 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(464, 418)
        Dialog.setWindowTitle(_fromUtf8(""))
        self.born_date_from = QtGui.QDateEdit(Dialog)
        self.born_date_from.setGeometry(QtCore.QRect(180, 160, 110, 22))
        self.born_date_from.setCalendarPopup(True)
        self.born_date_from.setObjectName(_fromUtf8("born_date_from"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 5, 20, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(12, 5, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(311, 5, 51, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(180, 140, 84, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gender = QtGui.QGroupBox(Dialog)
        self.gender.setGeometry(QtCore.QRect(10, 70, 112, 47))
        self.gender.setFlat(False)
        self.gender.setCheckable(False)
        self.gender.setObjectName(_fromUtf8("gender"))
        self.male = QtGui.QCheckBox(self.gender)
        self.male.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.male.setObjectName(_fromUtf8("male"))
        self.female = QtGui.QCheckBox(self.gender)
        self.female.setGeometry(QtCore.QRect(59, 20, 47, 17))
        self.female.setObjectName(_fromUtf8("female"))
        self.address_2 = QtGui.QLabel(Dialog)
        self.address_2.setGeometry(QtCore.QRect(170, 220, 86, 13))
        self.address_2.setObjectName(_fromUtf8("address_2"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(13, 140, 87, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.address = QtGui.QLineEdit(Dialog)
        self.address.setGeometry(QtCore.QRect(170, 240, 221, 20))
        self.address.setObjectName(_fromUtf8("address"))
        self.last_name = QtGui.QLineEdit(Dialog)
        self.last_name.setGeometry(QtCore.QRect(10, 20, 140, 20))
        self.last_name.setObjectName(_fromUtf8("last_name"))
        self.first_name = QtGui.QLineEdit(Dialog)
        self.first_name.setGeometry(QtCore.QRect(159, 20, 140, 20))
        self.first_name.setObjectName(_fromUtf8("first_name"))
        self.middle_name = QtGui.QLineEdit(Dialog)
        self.middle_name.setGeometry(QtCore.QRect(310, 20, 140, 20))
        self.middle_name.setObjectName(_fromUtf8("middle_name"))
        self.born_place = QtGui.QLineEdit(Dialog)
        self.born_place.setGeometry(QtCore.QRect(10, 160, 140, 20))
        self.born_place.setObjectName(_fromUtf8("born_place"))
        self.filterButton = QtGui.QPushButton(Dialog)
        self.filterButton.setGeometry(QtCore.QRect(10, 380, 75, 23))
        self.filterButton.setObjectName(_fromUtf8("filterButton"))
        self.resetButton = QtGui.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(90, 380, 75, 23))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.closeButton = QtGui.QPushButton(Dialog)
        self.closeButton.setGeometry(QtCore.QRect(170, 380, 75, 23))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 300, 91, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(168, 163, 12, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(301, 162, 17, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.born_date_to = QtGui.QDateEdit(Dialog)
        self.born_date_to.setGeometry(QtCore.QRect(320, 160, 110, 22))
        self.born_date_to.setCalendarPopup(True)
        self.born_date_to.setObjectName(_fromUtf8("born_date_to"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 88, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.address_city = QtGui.QLineEdit(Dialog)
        self.address_city.setGeometry(QtCore.QRect(10, 240, 140, 20))
        self.address_city.setObjectName(_fromUtf8("address_city"))
        self.born_place_type = QtGui.QCheckBox(Dialog)
        self.born_place_type.setGeometry(QtCore.QRect(10, 180, 120, 17))
        self.born_place_type.setObjectName(_fromUtf8("born_place_type"))
        self.last_name_type = QtGui.QCheckBox(Dialog)
        self.last_name_type.setGeometry(QtCore.QRect(10, 40, 120, 17))
        self.last_name_type.setObjectName(_fromUtf8("last_name_type"))
        self.first_name_type = QtGui.QCheckBox(Dialog)
        self.first_name_type.setGeometry(QtCore.QRect(160, 40, 120, 17))
        self.first_name_type.setObjectName(_fromUtf8("first_name_type"))
        self.middle_name_type = QtGui.QCheckBox(Dialog)
        self.middle_name_type.setGeometry(QtCore.QRect(310, 40, 120, 17))
        self.middle_name_type.setObjectName(_fromUtf8("middle_name_type"))
        self.address_sity_type = QtGui.QCheckBox(Dialog)
        self.address_sity_type.setGeometry(QtCore.QRect(10, 260, 120, 17))
        self.address_sity_type.setObjectName(_fromUtf8("address_sity_type"))
        self.address_type = QtGui.QCheckBox(Dialog)
        self.address_type.setGeometry(QtCore.QRect(170, 260, 120, 17))
        self.address_type.setObjectName(_fromUtf8("address_type"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(170, 300, 136, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.addiction_strat_date = QtGui.QSpinBox(Dialog)
        self.addiction_strat_date.setGeometry(QtCore.QRect(170, 320, 61, 22))
        self.addiction_strat_date.setObjectName(_fromUtf8("addiction_strat_date"))
        self.addiction_type_id = QtGui.QComboBox(Dialog)
        self.addiction_type_id.setGeometry(QtCore.QRect(10, 320, 141, 22))
        self.addiction_type_id.setObjectName(_fromUtf8("addiction_type_id"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.last_name, self.last_name_type)
        Dialog.setTabOrder(self.last_name_type, self.first_name)
        Dialog.setTabOrder(self.first_name, self.first_name_type)
        Dialog.setTabOrder(self.first_name_type, self.middle_name)
        Dialog.setTabOrder(self.middle_name, self.middle_name_type)
        Dialog.setTabOrder(self.middle_name_type, self.male)
        Dialog.setTabOrder(self.male, self.female)
        Dialog.setTabOrder(self.female, self.born_place)
        Dialog.setTabOrder(self.born_place, self.born_place_type)
        Dialog.setTabOrder(self.born_place_type, self.born_date_from)
        Dialog.setTabOrder(self.born_date_from, self.born_date_to)
        Dialog.setTabOrder(self.born_date_to, self.address_city)
        Dialog.setTabOrder(self.address_city, self.address_sity_type)
        Dialog.setTabOrder(self.address_sity_type, self.address)
        Dialog.setTabOrder(self.address, self.address_type)
        Dialog.setTabOrder(self.address_type, self.addiction_strat_date)
        Dialog.setTabOrder(self.addiction_strat_date, self.filterButton)
        Dialog.setTabOrder(self.filterButton, self.resetButton)
        Dialog.setTabOrder(self.resetButton, self.closeButton)

    def retranslateUi(self, Dialog):
        self.label.setText(QtGui.QApplication.translate("Dialog", "Имя", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Фамилия", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Отчество", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Дата рождения", None, QtGui.QApplication.UnicodeUTF8))
        self.gender.setTitle(QtGui.QApplication.translate("Dialog", "Пол", None, QtGui.QApplication.UnicodeUTF8))
        self.male.setText(QtGui.QApplication.translate("Dialog", "Муж.", None, QtGui.QApplication.UnicodeUTF8))
        self.female.setText(QtGui.QApplication.translate("Dialog", "Жен.", None, QtGui.QApplication.UnicodeUTF8))
        self.address_2.setText(QtGui.QApplication.translate("Dialog", "Адрес прописки", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Место рождения", None, QtGui.QApplication.UnicodeUTF8))
        self.filterButton.setText(QtGui.QApplication.translate("Dialog", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("Dialog", "Сбросить", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("Dialog", "Закрыть", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Тип зависимости", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "С", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "До", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Город прописки", None, QtGui.QApplication.UnicodeUTF8))
        self.born_place_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.last_name_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.first_name_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.middle_name_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.address_sity_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.address_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Длительность (в годах)", None, QtGui.QApplication.UnicodeUTF8))

