# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter_form.ui'
#
# Created: Sat Aug 13 16:27:25 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(507, 620)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/filter")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.filterButton = QtGui.QPushButton(Dialog)
        self.filterButton.setGeometry(QtCore.QRect(10, 585, 90, 26))
        self.filterButton.setIcon(icon)
        self.filterButton.setObjectName(_fromUtf8("filterButton"))
        self.resetButton = QtGui.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(110, 585, 90, 26))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/refresh")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetButton.setIcon(icon1)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.closeButton = QtGui.QPushButton(Dialog)
        self.closeButton.setGeometry(QtCore.QRect(210, 585, 90, 26))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(15, 14, 475, 281))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.born_date_label_from = QtGui.QLabel(self.groupBox)
        self.born_date_label_from.setEnabled(False)
        self.born_date_label_from.setGeometry(QtCore.QRect(184, 158, 12, 16))
        self.born_date_label_from.setObjectName(_fromUtf8("born_date_label_from"))
        self.address_type = QtGui.QCheckBox(self.groupBox)
        self.address_type.setGeometry(QtCore.QRect(196, 255, 120, 17))
        self.address_type.setObjectName(_fromUtf8("address_type"))
        self.first_name = QtGui.QLineEdit(self.groupBox)
        self.first_name.setGeometry(QtCore.QRect(165, 25, 140, 20))
        self.first_name.setObjectName(_fromUtf8("first_name"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(196, 78, 105, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gender = QtGui.QGroupBox(self.groupBox)
        self.gender.setGeometry(QtCore.QRect(16, 75, 150, 47))
        self.gender.setFlat(False)
        self.gender.setCheckable(False)
        self.gender.setObjectName(_fromUtf8("gender"))
        self.male = QtGui.QCheckBox(self.gender)
        self.male.setGeometry(QtCore.QRect(17, 18, 70, 17))
        self.male.setChecked(True)
        self.male.setObjectName(_fromUtf8("male"))
        self.female = QtGui.QCheckBox(self.gender)
        self.female.setGeometry(QtCore.QRect(83, 18, 47, 17))
        self.female.setChecked(True)
        self.female.setObjectName(_fromUtf8("female"))
        self.middle_name_type = QtGui.QCheckBox(self.groupBox)
        self.middle_name_type.setGeometry(QtCore.QRect(316, 45, 120, 17))
        self.middle_name_type.setObjectName(_fromUtf8("middle_name_type"))
        self.born_date_from = QtGui.QDateEdit(self.groupBox)
        self.born_date_from.setEnabled(False)
        self.born_date_from.setGeometry(QtCore.QRect(196, 155, 110, 22))
        self.born_date_from.setCalendarPopup(True)
        self.born_date_from.setObjectName(_fromUtf8("born_date_from"))
        self.born_date_label_to = QtGui.QLabel(self.groupBox)
        self.born_date_label_to.setEnabled(False)
        self.born_date_label_to.setGeometry(QtCore.QRect(327, 157, 17, 16))
        self.born_date_label_to.setObjectName(_fromUtf8("born_date_label_to"))
        self.first_name_type = QtGui.QCheckBox(self.groupBox)
        self.first_name_type.setGeometry(QtCore.QRect(166, 45, 120, 17))
        self.first_name_type.setObjectName(_fromUtf8("first_name_type"))
        self.last_name_type = QtGui.QCheckBox(self.groupBox)
        self.last_name_type.setGeometry(QtCore.QRect(16, 45, 120, 17))
        self.last_name_type.setObjectName(_fromUtf8("last_name_type"))
        self.address = QtGui.QLineEdit(self.groupBox)
        self.address.setGeometry(QtCore.QRect(196, 235, 140, 20))
        self.address.setObjectName(_fromUtf8("address"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(16, 215, 88, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.born_place_type = QtGui.QCheckBox(self.groupBox)
        self.born_place_type.setGeometry(QtCore.QRect(16, 175, 120, 17))
        self.born_place_type.setObjectName(_fromUtf8("born_place_type"))
        self.born_date_label = QtGui.QLabel(self.groupBox)
        self.born_date_label.setEnabled(True)
        self.born_date_label.setGeometry(QtCore.QRect(196, 135, 84, 16))
        self.born_date_label.setObjectName(_fromUtf8("born_date_label"))
        self.born_date_to = QtGui.QDateEdit(self.groupBox)
        self.born_date_to.setEnabled(False)
        self.born_date_to.setGeometry(QtCore.QRect(346, 155, 110, 22))
        self.born_date_to.setCalendarPopup(True)
        self.born_date_to.setObjectName(_fromUtf8("born_date_to"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(19, 135, 87, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.middle_name = QtGui.QLineEdit(self.groupBox)
        self.middle_name.setGeometry(QtCore.QRect(316, 25, 140, 20))
        self.middle_name.setObjectName(_fromUtf8("middle_name"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(317, 10, 51, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(18, 10, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.last_name = QtGui.QLineEdit(self.groupBox)
        self.last_name.setGeometry(QtCore.QRect(16, 25, 140, 20))
        self.last_name.setObjectName(_fromUtf8("last_name"))
        self.born_place = QtGui.QLineEdit(self.groupBox)
        self.born_place.setGeometry(QtCore.QRect(16, 155, 150, 20))
        self.born_place.setObjectName(_fromUtf8("born_place"))
        self.born_date_enabled = QtGui.QCheckBox(self.groupBox)
        self.born_date_enabled.setGeometry(QtCore.QRect(196, 177, 71, 17))
        self.born_date_enabled.setObjectName(_fromUtf8("born_date_enabled"))
        self.passport = QtGui.QLineEdit(self.groupBox)
        self.passport.setGeometry(QtCore.QRect(196, 95, 260, 20))
        self.passport.setInputMask(_fromUtf8(""))
        self.passport.setText(_fromUtf8(""))
        self.passport.setObjectName(_fromUtf8("passport"))
        self.address_2 = QtGui.QLabel(self.groupBox)
        self.address_2.setGeometry(QtCore.QRect(196, 215, 86, 13))
        self.address_2.setObjectName(_fromUtf8("address_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(166, 10, 20, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.address_city = QtGui.QLineEdit(self.groupBox)
        self.address_city.setGeometry(QtCore.QRect(16, 235, 150, 20))
        self.address_city.setObjectName(_fromUtf8("address_city"))
        self.conviction = QtGui.QComboBox(self.groupBox)
        self.conviction.setGeometry(QtCore.QRect(353, 234, 101, 22))
        self.conviction.setObjectName(_fromUtf8("conviction"))
        self.conviction.addItem(_fromUtf8(""))
        self.conviction.addItem(_fromUtf8(""))
        self.conviction.addItem(_fromUtf8(""))
        self.address_3 = QtGui.QLabel(self.groupBox)
        self.address_3.setGeometry(QtCore.QRect(354, 215, 60, 13))
        self.address_3.setObjectName(_fromUtf8("address_3"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(15, 293, 475, 118))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(16, 7, 91, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.remission_from = QtGui.QLineEdit(self.groupBox_2)
        self.remission_from.setGeometry(QtCore.QRect(197, 83, 110, 20))
        self.remission_from.setText(_fromUtf8(""))
        self.remission_from.setObjectName(_fromUtf8("remission_from"))
        self.born_date_label_from_5 = QtGui.QLabel(self.groupBox_2)
        self.born_date_label_from_5.setEnabled(True)
        self.born_date_label_from_5.setGeometry(QtCore.QRect(179, 85, 15, 16))
        self.born_date_label_from_5.setObjectName(_fromUtf8("born_date_label_from_5"))
        self.born_date_label_from_3 = QtGui.QLabel(self.groupBox_2)
        self.born_date_label_from_3.setEnabled(True)
        self.born_date_label_from_3.setGeometry(QtCore.QRect(267, 30, 20, 16))
        self.born_date_label_from_3.setText(_fromUtf8(""))
        self.born_date_label_from_3.setObjectName(_fromUtf8("born_date_label_from_3"))
        self.born_date_label_from_2 = QtGui.QLabel(self.groupBox_2)
        self.born_date_label_from_2.setEnabled(True)
        self.born_date_label_from_2.setGeometry(QtCore.QRect(179, 29, 15, 16))
        self.born_date_label_from_2.setObjectName(_fromUtf8("born_date_label_from_2"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(199, 7, 136, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(199, 63, 180, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.born_date_label_from_4 = QtGui.QLabel(self.groupBox_2)
        self.born_date_label_from_4.setEnabled(True)
        self.born_date_label_from_4.setGeometry(QtCore.QRect(322, 28, 15, 16))
        self.born_date_label_from_4.setObjectName(_fromUtf8("born_date_label_from_4"))
        self.addiction_type = QtGui.QComboBox(self.groupBox_2)
        self.addiction_type.setGeometry(QtCore.QRect(16, 27, 150, 22))
        self.addiction_type.setObjectName(_fromUtf8("addiction_type"))
        self.addiction_duration_from = QtGui.QLineEdit(self.groupBox_2)
        self.addiction_duration_from.setGeometry(QtCore.QRect(197, 27, 110, 20))
        self.addiction_duration_from.setText(_fromUtf8(""))
        self.addiction_duration_from.setObjectName(_fromUtf8("addiction_duration_from"))
        self.addiction_duration_to = QtGui.QLineEdit(self.groupBox_2)
        self.addiction_duration_to.setGeometry(QtCore.QRect(345, 27, 110, 20))
        self.addiction_duration_to.setText(_fromUtf8(""))
        self.addiction_duration_to.setObjectName(_fromUtf8("addiction_duration_to"))
        self.born_date_label_from_6 = QtGui.QLabel(self.groupBox_2)
        self.born_date_label_from_6.setEnabled(True)
        self.born_date_label_from_6.setGeometry(QtCore.QRect(322, 84, 15, 16))
        self.born_date_label_from_6.setObjectName(_fromUtf8("born_date_label_from_6"))
        self.remission_to = QtGui.QLineEdit(self.groupBox_2)
        self.remission_to.setGeometry(QtCore.QRect(345, 83, 110, 20))
        self.remission_to.setText(_fromUtf8(""))
        self.remission_to.setObjectName(_fromUtf8("remission_to"))
        self.reabilitation = QtGui.QCheckBox(self.groupBox_2)
        self.reabilitation.setGeometry(QtCore.QRect(17, 58, 190, 41))
        self.reabilitation.setObjectName(_fromUtf8("reabilitation"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(15, 409, 475, 155))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.born_date_label_2 = QtGui.QLabel(self.groupBox_3)
        self.born_date_label_2.setEnabled(True)
        self.born_date_label_2.setGeometry(QtCore.QRect(195, 13, 150, 16))
        self.born_date_label_2.setObjectName(_fromUtf8("born_date_label_2"))
        self.send_date_from = QtGui.QDateEdit(self.groupBox_3)
        self.send_date_from.setEnabled(False)
        self.send_date_from.setGeometry(QtCore.QRect(195, 33, 110, 22))
        self.send_date_from.setCalendarPopup(True)
        self.send_date_from.setObjectName(_fromUtf8("send_date_from"))
        self.send_date_from_label = QtGui.QLabel(self.groupBox_3)
        self.send_date_from_label.setEnabled(False)
        self.send_date_from_label.setGeometry(QtCore.QRect(183, 36, 12, 16))
        self.send_date_from_label.setObjectName(_fromUtf8("send_date_from_label"))
        self.arrive_date_from_label = QtGui.QLabel(self.groupBox_3)
        self.arrive_date_from_label.setEnabled(False)
        self.arrive_date_from_label.setGeometry(QtCore.QRect(183, 108, 12, 16))
        self.arrive_date_from_label.setObjectName(_fromUtf8("arrive_date_from_label"))
        self.arrive_date_to = QtGui.QDateEdit(self.groupBox_3)
        self.arrive_date_to.setEnabled(False)
        self.arrive_date_to.setGeometry(QtCore.QRect(345, 105, 110, 22))
        self.arrive_date_to.setCalendarPopup(True)
        self.arrive_date_to.setObjectName(_fromUtf8("arrive_date_to"))
        self.arrive_date_from_enable = QtGui.QCheckBox(self.groupBox_3)
        self.arrive_date_from_enable.setGeometry(QtCore.QRect(195, 127, 71, 17))
        self.arrive_date_from_enable.setObjectName(_fromUtf8("arrive_date_from_enable"))
        self.send_address_enable = QtGui.QCheckBox(self.groupBox_3)
        self.send_address_enable.setGeometry(QtCore.QRect(16, 55, 71, 17))
        self.send_address_enable.setObjectName(_fromUtf8("send_address_enable"))
        self.arrive_date_to_label = QtGui.QLabel(self.groupBox_3)
        self.arrive_date_to_label.setEnabled(False)
        self.arrive_date_to_label.setGeometry(QtCore.QRect(326, 107, 17, 16))
        self.arrive_date_to_label.setObjectName(_fromUtf8("arrive_date_to_label"))
        self.send_date_to = QtGui.QDateEdit(self.groupBox_3)
        self.send_date_to.setEnabled(False)
        self.send_date_to.setGeometry(QtCore.QRect(345, 33, 110, 22))
        self.send_date_to.setCalendarPopup(True)
        self.send_date_to.setObjectName(_fromUtf8("send_date_to"))
        self.arrive_date_from = QtGui.QDateEdit(self.groupBox_3)
        self.arrive_date_from.setEnabled(False)
        self.arrive_date_from.setGeometry(QtCore.QRect(195, 105, 110, 22))
        self.arrive_date_from.setCalendarPopup(True)
        self.arrive_date_from.setObjectName(_fromUtf8("arrive_date_from"))
        self.send_date_from_enable = QtGui.QCheckBox(self.groupBox_3)
        self.send_date_from_enable.setGeometry(QtCore.QRect(195, 55, 71, 17))
        self.send_date_from_enable.setObjectName(_fromUtf8("send_date_from_enable"))
        self.send_address = QtGui.QComboBox(self.groupBox_3)
        self.send_address.setEnabled(False)
        self.send_address.setGeometry(QtCore.QRect(16, 33, 141, 22))
        self.send_address.setObjectName(_fromUtf8("send_address"))
        self.arrive_date_to_enable = QtGui.QCheckBox(self.groupBox_3)
        self.arrive_date_to_enable.setGeometry(QtCore.QRect(345, 127, 71, 17))
        self.arrive_date_to_enable.setObjectName(_fromUtf8("arrive_date_to_enable"))
        self.send_address_label = QtGui.QLabel(self.groupBox_3)
        self.send_address_label.setEnabled(False)
        self.send_address_label.setGeometry(QtCore.QRect(16, 13, 160, 16))
        self.send_address_label.setObjectName(_fromUtf8("send_address_label"))
        self.born_date_label_3 = QtGui.QLabel(self.groupBox_3)
        self.born_date_label_3.setEnabled(True)
        self.born_date_label_3.setGeometry(QtCore.QRect(195, 85, 86, 16))
        self.born_date_label_3.setObjectName(_fromUtf8("born_date_label_3"))
        self.send_date_to_enable = QtGui.QCheckBox(self.groupBox_3)
        self.send_date_to_enable.setGeometry(QtCore.QRect(345, 55, 71, 17))
        self.send_date_to_enable.setObjectName(_fromUtf8("send_date_to_enable"))
        self.send_date_to_label = QtGui.QLabel(self.groupBox_3)
        self.send_date_to_label.setEnabled(False)
        self.send_date_to_label.setGeometry(QtCore.QRect(326, 35, 17, 16))
        self.send_date_to_label.setObjectName(_fromUtf8("send_date_to_label"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.filterButton, self.resetButton)
        Dialog.setTabOrder(self.resetButton, self.closeButton)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Фильтр базы", None, QtGui.QApplication.UnicodeUTF8))
        self.filterButton.setText(QtGui.QApplication.translate("Dialog", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("Dialog", "Сбросить", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("Dialog", "Закрыть", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_from.setText(QtGui.QApplication.translate("Dialog", "С", None, QtGui.QApplication.UnicodeUTF8))
        self.address_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Паспорт (Серия, №)", None, QtGui.QApplication.UnicodeUTF8))
        self.gender.setTitle(QtGui.QApplication.translate("Dialog", "Пол", None, QtGui.QApplication.UnicodeUTF8))
        self.male.setText(QtGui.QApplication.translate("Dialog", "Муж.", None, QtGui.QApplication.UnicodeUTF8))
        self.female.setText(QtGui.QApplication.translate("Dialog", "Жен.", None, QtGui.QApplication.UnicodeUTF8))
        self.middle_name_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_to.setText(QtGui.QApplication.translate("Dialog", "До", None, QtGui.QApplication.UnicodeUTF8))
        self.first_name_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.last_name_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Город прописки", None, QtGui.QApplication.UnicodeUTF8))
        self.born_place_type.setText(QtGui.QApplication.translate("Dialog", "точное совпадение", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label.setText(QtGui.QApplication.translate("Dialog", "Дата рождения", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Место рождения", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Отчество", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Фамилия", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_enabled.setText(QtGui.QApplication.translate("Dialog", "включить", None, QtGui.QApplication.UnicodeUTF8))
        self.address_2.setText(QtGui.QApplication.translate("Dialog", "Адрес прописки", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Имя", None, QtGui.QApplication.UnicodeUTF8))
        self.conviction.setItemText(0, QtGui.QApplication.translate("Dialog", "Не учитывать", None, QtGui.QApplication.UnicodeUTF8))
        self.conviction.setItemText(1, QtGui.QApplication.translate("Dialog", "Есть", None, QtGui.QApplication.UnicodeUTF8))
        self.conviction.setItemText(2, QtGui.QApplication.translate("Dialog", "Нет", None, QtGui.QApplication.UnicodeUTF8))
        self.address_3.setText(QtGui.QApplication.translate("Dialog", "Судимость", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Зависимость", None, QtGui.QApplication.UnicodeUTF8))
        self.remission_from.setInputMask(QtGui.QApplication.translate("Dialog", "####; ", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_from_5.setText(QtGui.QApplication.translate("Dialog", "От", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_from_2.setText(QtGui.QApplication.translate("Dialog", "От", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Длительность (в годах)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Длительность ремиссии (в годах)", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_from_4.setText(QtGui.QApplication.translate("Dialog", "До", None, QtGui.QApplication.UnicodeUTF8))
        self.addiction_duration_from.setInputMask(QtGui.QApplication.translate("Dialog", "####; ", None, QtGui.QApplication.UnicodeUTF8))
        self.addiction_duration_to.setInputMask(QtGui.QApplication.translate("Dialog", "####; ", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_from_6.setText(QtGui.QApplication.translate("Dialog", "До", None, QtGui.QApplication.UnicodeUTF8))
        self.remission_to.setInputMask(QtGui.QApplication.translate("Dialog", "####; ", None, QtGui.QApplication.UnicodeUTF8))
        self.reabilitation.setText(QtGui.QApplication.translate("Dialog", "Был в реабилитации от 5\n"
"и более месяцев", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_2.setText(QtGui.QApplication.translate("Dialog", "Дата отправки в ад-цию", None, QtGui.QApplication.UnicodeUTF8))
        self.send_date_from_label.setText(QtGui.QApplication.translate("Dialog", "С", None, QtGui.QApplication.UnicodeUTF8))
        self.arrive_date_from_label.setText(QtGui.QApplication.translate("Dialog", "С", None, QtGui.QApplication.UnicodeUTF8))
        self.arrive_date_from_enable.setText(QtGui.QApplication.translate("Dialog", "включить", None, QtGui.QApplication.UnicodeUTF8))
        self.send_address_enable.setText(QtGui.QApplication.translate("Dialog", "включить", None, QtGui.QApplication.UnicodeUTF8))
        self.arrive_date_to_label.setText(QtGui.QApplication.translate("Dialog", "До", None, QtGui.QApplication.UnicodeUTF8))
        self.send_date_from_enable.setText(QtGui.QApplication.translate("Dialog", "включить", None, QtGui.QApplication.UnicodeUTF8))
        self.arrive_date_to_enable.setText(QtGui.QApplication.translate("Dialog", "включить", None, QtGui.QApplication.UnicodeUTF8))
        self.send_address_label.setText(QtGui.QApplication.translate("Dialog", "Место отправки в ад-цию", None, QtGui.QApplication.UnicodeUTF8))
        self.born_date_label_3.setText(QtGui.QApplication.translate("Dialog", "Дата прибытия", None, QtGui.QApplication.UnicodeUTF8))
        self.send_date_to_enable.setText(QtGui.QApplication.translate("Dialog", "включить", None, QtGui.QApplication.UnicodeUTF8))
        self.send_date_to_label.setText(QtGui.QApplication.translate("Dialog", "До", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
