# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Tue Jul 12 01:22:00 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(900, 539)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/logo")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(3, 1, 891, 491))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.mainLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.mainLayout.setMargin(0)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.mainTable = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.mainTable.setAutoFillBackground(False)
        self.mainTable.setStyleSheet(_fromUtf8("background-color: rgb(248, 248, 209);"))
        self.mainTable.setFrameShadow(QtGui.QFrame.Sunken)
        self.mainTable.setMidLineWidth(0)
        self.mainTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.mainTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.mainTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.mainTable.setGridStyle(QtCore.Qt.SolidLine)
        self.mainTable.setObjectName(_fromUtf8("mainTable"))
        self.mainTable.setColumnCount(0)
        self.mainTable.setRowCount(0)
        self.mainTable.verticalHeader().setVisible(True)
        self.mainLayout.addWidget(self.mainTable)
        self.buttonBar = QtGui.QHBoxLayout()
        self.buttonBar.setObjectName(_fromUtf8("buttonBar"))
        self.buttonBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonBox.setMaximumSize(QtCore.QSize(500, 16777215))
        self.buttonBox.setTitle(_fromUtf8(""))
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.buttonBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1, 1, 496, 28))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.buttonBoxLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.buttonBoxLayout.setMargin(0)
        self.buttonBoxLayout.setObjectName(_fromUtf8("buttonBoxLayout"))
        self.openButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.openButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        self.openButton.setMaximumSize(QtCore.QSize(150, 26))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/edit_person")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openButton.setIcon(icon1)
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.buttonBoxLayout.addWidget(self.openButton)
        self.addButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.addButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMaximumSize(QtCore.QSize(150, 26))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/add_person")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon2)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.buttonBoxLayout.addWidget(self.addButton)
        self.deleteButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.deleteButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setMaximumSize(QtCore.QSize(150, 26))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/delete_person")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon3)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.buttonBoxLayout.addWidget(self.deleteButton)
        self.filterButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.filterButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterButton.sizePolicy().hasHeightForWidth())
        self.filterButton.setSizePolicy(sizePolicy)
        self.filterButton.setMaximumSize(QtCore.QSize(150, 26))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/filter")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filterButton.setIcon(icon4)
        self.filterButton.setObjectName(_fromUtf8("filterButton"))
        self.buttonBoxLayout.addWidget(self.filterButton)
        self.refreshButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.refreshButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshButton.sizePolicy().hasHeightForWidth())
        self.refreshButton.setSizePolicy(sizePolicy)
        self.refreshButton.setMaximumSize(QtCore.QSize(150, 26))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/refresh")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon5)
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.buttonBoxLayout.addWidget(self.refreshButton)
        self.buttonBar.addWidget(self.buttonBox)
        self.mainLayout.addLayout(self.buttonBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.editMeny = QtGui.QMenu(self.menubar)
        self.editMeny.setObjectName(_fromUtf8("editMeny"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.openBaseAction = QtGui.QAction(MainWindow)
        self.openBaseAction.setObjectName(_fromUtf8("openBaseAction"))
        self.exitAction = QtGui.QAction(MainWindow)
        self.exitAction.setObjectName(_fromUtf8("exitAction"))
        self.createBaseAction = QtGui.QAction(MainWindow)
        self.createBaseAction.setObjectName(_fromUtf8("createBaseAction"))
        self.imagesPathEditAction = QtGui.QAction(MainWindow)
        self.imagesPathEditAction.setObjectName(_fromUtf8("imagesPathEditAction"))
        self.catalogEditAction = QtGui.QAction(MainWindow)
        self.catalogEditAction.setEnabled(False)
        self.catalogEditAction.setObjectName(_fromUtf8("catalogEditAction"))
        self.menu.addAction(self.createBaseAction)
        self.menu.addAction(self.openBaseAction)
        self.menu.addSeparator()
        self.menu.addAction(self.exitAction)
        self.editMeny.addAction(self.imagesPathEditAction)
        self.editMeny.addAction(self.catalogEditAction)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.editMeny.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.exitAction, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Новый свет - База данных", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTable.setSortingEnabled(True)
        self.openButton.setText(QtGui.QApplication.translate("MainWindow", "Открыть", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("MainWindow", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("MainWindow", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.filterButton.setText(QtGui.QApplication.translate("MainWindow", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshButton.setText(QtGui.QApplication.translate("MainWindow", "Сбросить", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.editMeny.setTitle(QtGui.QApplication.translate("MainWindow", "Правка", None, QtGui.QApplication.UnicodeUTF8))
        self.openBaseAction.setText(QtGui.QApplication.translate("MainWindow", "Открыть базу...", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setText(QtGui.QApplication.translate("MainWindow", "Выход", None, QtGui.QApplication.UnicodeUTF8))
        self.createBaseAction.setText(QtGui.QApplication.translate("MainWindow", "Создать пустую базу...", None, QtGui.QApplication.UnicodeUTF8))
        self.imagesPathEditAction.setText(QtGui.QApplication.translate("MainWindow", "Изменить директоррию фотографий...", None, QtGui.QApplication.UnicodeUTF8))
        self.catalogEditAction.setText(QtGui.QApplication.translate("MainWindow", "Изменить справочники...", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
